theme: jekyll-theme-hacker
title: Holt Skinner
author:
  name: Holt Skinner
  email: skinnerholt@gmail.com
description: Holt Skinner, Cloud Engineer & Countertenor: Technology Enthusiast, Classical Singer, Coffee Fanatic, Mental Health Advocate ğŸ’»ğŸ¤“â˜•ï¸ğŸ¼ğŸµğŸ§©ğŸ§ 
github_username: holtskinner
linkedin_username: holt
year: 2021
